"""Baseline consolidado do schema PostgreSQL validado em 2026-08-03.

Esta revisão é o ponto inicial para bancos novos. Bancos sem histórico Alembic
compatível não são adotados automaticamente.
"""

from alembic import op

revision = "20260803_0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE SCHEMA IF NOT EXISTS historico")
    op.execute("CREATE SCHEMA IF NOT EXISTS dados_entrada")
    op.execute("""
    CREATE TABLE historico.configuracoes (chave TEXT PRIMARY KEY, valor TEXT NOT NULL, atualizado_em TEXT NOT NULL);
    CREATE TABLE historico.usuarios (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT NOT NULL, login CITEXT NOT NULL UNIQUE, senha_hash TEXT NOT NULL, perfil TEXT NOT NULL, ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, ultimo_login_em TEXT);
    CREATE TABLE historico.zonas (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT NOT NULL, especie TEXT NOT NULL, indice TEXT NOT NULL, ativa INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL);
    CREATE TABLE historico.leituras (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, especie TEXT NOT NULL, indice TEXT NOT NULL, valor DOUBLE PRECISION NOT NULL, status TEXT NOT NULL, entradas JSONB NOT NULL, criado_em TEXT NOT NULL, zona_id BIGINT REFERENCES historico.zonas(id) ON DELETE SET NULL);
    CREATE TABLE historico.equipamentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, zona_id BIGINT NOT NULL REFERENCES historico.zonas(id) ON DELETE CASCADE, tipo TEXT NOT NULL, nome TEXT NOT NULL, modo_conexao TEXT NOT NULL, host TEXT, porta INTEGER, porta_serial TEXT, baud_rate INTEGER, unidade_id INTEGER NOT NULL DEFAULT 1, tipo_registrador TEXT NOT NULL, endereco_registrador INTEGER NOT NULL, tipo_dado TEXT NOT NULL DEFAULT 'int16', fator_escala DOUBLE PRECISION NOT NULL DEFAULT 1.0, campo_medido TEXT, criado_em TEXT NOT NULL);
    CREATE TABLE historico.estado_equipamentos (zona_id BIGINT PRIMARY KEY REFERENCES historico.zonas(id) ON DELETE CASCADE, ventilador_ligado INTEGER NOT NULL DEFAULT 0, nebulizador_ligado INTEGER NOT NULL DEFAULT 0, intensidade TEXT, atualizado_em TEXT NOT NULL, ventilador_desejado INTEGER, nebulizador_desejado INTEGER, ventilador_confirmado INTEGER, nebulizador_confirmado INTEGER, falhas JSONB NOT NULL DEFAULT '[]'::jsonb, qualidade TEXT NOT NULL DEFAULT 'sem_leitura', ultimo_ciclo_em TEXT);
    CREATE TABLE historico.controle_zonas (zona_id BIGINT PRIMARY KEY REFERENCES historico.zonas(id) ON DELETE CASCADE, modo TEXT NOT NULL DEFAULT 'manual', acionamento_habilitado INTEGER NOT NULL DEFAULT 0, atualizado_em TEXT NOT NULL);
    CREATE TABLE historico.estado_coletor (id INTEGER PRIMARY KEY CHECK (id = 1), status TEXT NOT NULL, iniciado_em TEXT, heartbeat_em TEXT, ultimo_ciclo_em TEXT, proximo_ciclo_em TEXT, erro TEXT);
    CREATE TABLE historico.eventos_operacao (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, zona_id BIGINT REFERENCES historico.zonas(id) ON DELETE SET NULL, tipo TEXT NOT NULL, acao TEXT NOT NULL, detalhes JSONB NOT NULL, criado_em TEXT NOT NULL);
    CREATE TABLE historico.leituras_recentes_zona (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, zona_id BIGINT NOT NULL REFERENCES historico.zonas(id) ON DELETE CASCADE, especie TEXT NOT NULL, indice TEXT NOT NULL, valor DOUBLE PRECISION NOT NULL, status TEXT NOT NULL, entradas JSONB NOT NULL, criado_em TEXT NOT NULL);
    CREATE TABLE historico.agregados_15min (zona_id BIGINT NOT NULL REFERENCES historico.zonas(id) ON DELETE CASCADE, especie TEXT NOT NULL, indice TEXT NOT NULL, janela_inicio TEXT NOT NULL, amostras INTEGER NOT NULL, valor_medio DOUBLE PRECISION NOT NULL, valor_minimo DOUBLE PRECISION NOT NULL, valor_maximo DOUBLE PRECISION NOT NULL, entradas_medias JSONB NOT NULL, criado_em TEXT NOT NULL, PRIMARY KEY (zona_id, indice, janela_inicio));
    CREATE TABLE historico.resumos_horarios (zona_id BIGINT NOT NULL REFERENCES historico.zonas(id) ON DELETE CASCADE, especie TEXT NOT NULL, indice TEXT NOT NULL, hora_inicio TEXT NOT NULL, amostras INTEGER NOT NULL, valor_medio DOUBLE PRECISION NOT NULL, valor_minimo DOUBLE PRECISION NOT NULL, valor_maximo DOUBLE PRECISION NOT NULL, status_da_media TEXT NOT NULL, pct_conforto DOUBLE PRECISION NOT NULL, pct_alerta DOUBLE PRECISION NOT NULL, pct_perigo DOUBLE PRECISION NOT NULL, pct_emergencia DOUBLE PRECISION NOT NULL, criado_em TEXT NOT NULL, PRIMARY KEY (zona_id, indice, hora_inicio));
    CREATE TABLE dados_entrada.configuracoes_zona (zona_id BIGINT PRIMARY KEY, zona_nome TEXT NOT NULL, especie TEXT NOT NULL, cidade_codigo_ibge TEXT, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, fuso_horario TEXT NOT NULL DEFAULT 'America/Sao_Paulo', altitude_m DOUBLE PRECISION, area_util_m2 DOUBLE PRECISION, densidade_categoria TEXT NOT NULL DEFAULT 'media', densidade_animais_m2 DOUBLE PRECISION, quantidade_animais INTEGER NOT NULL DEFAULT 0, peso_medio_kg DOUBLE PRECISION, producao_leite_kg_dia DOUBLE PRECISION NOT NULL DEFAULT 0, ordenhas_dia INTEGER NOT NULL DEFAULT 0, atualizado_em TEXT NOT NULL);
    CREATE TABLE dados_entrada.execucoes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, data_inicio TEXT NOT NULL, data_fim TEXT NOT NULL, dias INTEGER NOT NULL, intervalo_minutos INTEGER NOT NULL, semente BIGINT NOT NULL, fonte_clima TEXT NOT NULL, total_zonas INTEGER NOT NULL, total_medicoes BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL, erro TEXT, criado_em TEXT NOT NULL, concluido_em TEXT);
    CREATE TABLE dados_entrada.medicoes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, execucao_id BIGINT NOT NULL REFERENCES dados_entrada.execucoes(id) ON DELETE CASCADE, zona_id BIGINT NOT NULL, zona_nome TEXT NOT NULL, especie TEXT NOT NULL, indice TEXT NOT NULL, timestamp_utc TEXT NOT NULL, timestamp_local TEXT NOT NULL, fuso_horario TEXT NOT NULL, tbs_externa_c DOUBLE PRECISION NOT NULL, ur_externa_pct DOUBLE PRECISION NOT NULL, ponto_orvalho_c DOUBLE PRECISION NOT NULL, tbu_c DOUBLE PRECISION NOT NULL, velocidade_vento_ms DOUBLE PRECISION NOT NULL, precipitacao_mm DOUBLE PRECISION, pressao_hpa DOUBLE PRECISION, radiacao_w_m2 DOUBLE PRECISION, nebulosidade_pct DOUBLE PRECISION, valor_indice DOUBLE PRECISION NOT NULL, status_termico TEXT NOT NULL, area_util_m2 DOUBLE PRECISION NOT NULL, densidade_categoria TEXT NOT NULL, densidade_animais_m2 DOUBLE PRECISION NOT NULL, quantidade_animais INTEGER NOT NULL, atividade_predominante TEXT NOT NULL, alimentacao_kg DOUBLE PRECISION NOT NULL, consumo_agua_l DOUBLE PRECISION NOT NULL, animais_em_pe INTEGER NOT NULL, animais_deitados INTEGER NOT NULL, animais_em_ordenha INTEGER NOT NULL, calor_sensivel_animais_w DOUBLE PRECISION NOT NULL, calor_latente_animais_w DOUBLE PRECISION NOT NULL, vapor_agua_animais_kg_h DOUBLE PRECISION NOT NULL, origem_variaveis JSONB NOT NULL, indicador_qualidade TEXT NOT NULL, entradas_indice JSONB NOT NULL, simulation_seed BIGINT NOT NULL, UNIQUE (execucao_id, zona_id, timestamp_utc));
    CREATE TABLE dados_entrada.cache_clima (chave TEXT PRIMARY KEY, resposta_json JSONB NOT NULL, fonte TEXT NOT NULL, consultado_em TEXT NOT NULL);
    CREATE TABLE dados_entrada.historico_exportado (medicao_id BIGINT PRIMARY KEY REFERENCES dados_entrada.medicoes(id) ON DELETE CASCADE, copiado_em TEXT NOT NULL);
    CREATE INDEX idx_zonas_ativa ON historico.zonas (ativa);
    CREATE INDEX idx_leituras_especie_indice_id ON historico.leituras (especie, indice, id);
    CREATE INDEX idx_leituras_zona_indice_id ON historico.leituras (zona_id, indice, id);
    CREATE INDEX idx_leituras_zona_indice_criado_em ON historico.leituras (zona_id, indice, criado_em);
    CREATE INDEX idx_leituras_criado_em_id ON historico.leituras (criado_em, id);
    CREATE INDEX idx_equipamentos_zona_id ON historico.equipamentos (zona_id);
    CREATE INDEX idx_eventos_operacao_zona_id ON historico.eventos_operacao (zona_id, id);
    CREATE INDEX idx_leituras_recentes_zona_id ON historico.leituras_recentes_zona (zona_id, id);
    CREATE INDEX idx_agregados_15min_zona ON historico.agregados_15min (zona_id, janela_inicio);
    CREATE INDEX idx_resumos_horarios_zona ON historico.resumos_horarios (zona_id, hora_inicio);
    CREATE INDEX idx_medicoes_execucao_zona_data ON dados_entrada.medicoes (execucao_id, zona_id, timestamp_utc);
    """)


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS dados_entrada CASCADE")
    op.execute("DROP SCHEMA IF EXISTS historico CASCADE")
