"""Auditoria consultável e política de frescor por zona.

As colunas usam padrões compatíveis com a imagem anterior: ela continua a
ignorar o novo campo de zona, e a tabela de auditoria é aditiva.
"""

from alembic import op

revision = "20260901_0001_audit_frescor"
down_revision = "20260830_0001_trocar_senha"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE historico.zonas "
        "ADD COLUMN ciclos_expiracao_leitura INTEGER NOT NULL DEFAULT 3 "
        "CHECK (ciclos_expiracao_leitura BETWEEN 2 AND 3)"
    )
    op.execute(
        """
        CREATE TABLE historico.auditoria_eventos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            evento TEXT NOT NULL,
            categoria TEXT NOT NULL,
            acao TEXT NOT NULL,
            sucesso INTEGER NOT NULL,
            ator_id BIGINT,
            ator_login TEXT NOT NULL,
            ator_perfil TEXT NOT NULL,
            contexto JSONB NOT NULL,
            detalhes JSONB NOT NULL,
            criado_em TEXT NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_auditoria_eventos_criado_em "
        "ON historico.auditoria_eventos (criado_em DESC)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE historico.auditoria_eventos")
    op.execute("ALTER TABLE historico.zonas DROP COLUMN ciclos_expiracao_leitura")
