"""Integridade de amostras, outbox de notificações e leases de geração.

Esta revisão é aditiva. Timestamps antigos continuam em ``TEXT`` para não
quebrar consumidores existentes; o código novo grava ISO-8601 com offset UTC
e interpreta o formato legado sem offset como UTC.
"""

from alembic import op


revision = "20260919_01_integridade"
down_revision = "20260905_0001_status_sem_acento"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE historico.leituras ADD COLUMN timestamp_utc TEXT")
    op.execute("ALTER TABLE historico.leituras ADD COLUMN amostra_id TEXT")
    op.execute(
        "UPDATE historico.leituras SET timestamp_utc = criado_em "
        "WHERE timestamp_utc IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_leituras_identidade_amostra "
        "ON historico.leituras (zona_id, indice, amostra_id) "
        "WHERE amostra_id IS NOT NULL"
    )

    op.execute("ALTER TABLE dados_entrada.execucoes ADD COLUMN lease_token TEXT")
    op.execute("ALTER TABLE dados_entrada.execucoes ADD COLUMN lease_until TEXT")
    op.execute("ALTER TABLE dados_entrada.execucoes ADD COLUMN heartbeat_em TEXT")
    op.execute("ALTER TABLE dados_entrada.execucoes ADD COLUMN publicado_em TEXT")
    op.execute(
        "CREATE INDEX idx_execucoes_lease ON dados_entrada.execucoes "
        "(status, lease_until)"
    )

    op.execute(
        """
        CREATE TABLE historico.notificacoes_outbox (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dedupe_key TEXT NOT NULL UNIQUE,
            destino TEXT NOT NULL,
            conteudo TEXT NOT NULL,
            smtp_config JSONB NOT NULL,
            status TEXT NOT NULL DEFAULT 'pendente',
            tentativas INTEGER NOT NULL DEFAULT 0,
            proxima_tentativa_em TEXT,
            bloqueado_em TEXT,
            criado_em TEXT NOT NULL,
            enviado_em TEXT,
            ultimo_erro TEXT
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_notificacoes_outbox_pendentes "
        "ON historico.notificacoes_outbox (status, proxima_tentativa_em, id)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS historico.idx_notificacoes_outbox_pendentes")
    op.execute("DROP TABLE historico.notificacoes_outbox")
    op.execute("DROP INDEX IF EXISTS dados_entrada.idx_execucoes_lease")
    op.execute("ALTER TABLE dados_entrada.execucoes DROP COLUMN publicado_em")
    op.execute("ALTER TABLE dados_entrada.execucoes DROP COLUMN heartbeat_em")
    op.execute("ALTER TABLE dados_entrada.execucoes DROP COLUMN lease_until")
    op.execute("ALTER TABLE dados_entrada.execucoes DROP COLUMN lease_token")
    op.execute("DROP INDEX IF EXISTS historico.uq_leituras_identidade_amostra")
    op.execute("ALTER TABLE historico.leituras DROP COLUMN amostra_id")
    op.execute("ALTER TABLE historico.leituras DROP COLUMN timestamp_utc")
